services:
  core:
    container_name: main
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./JobsParana:/jobs
      - ./static:/data/web/static/
    env_file:
      - dotenv_files/.env
    depends_on:
      - database
  database:
    container_name: database
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - dotenv_files/.env