# Generated by Django 5.1.2 on 2024-10-19 23:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_company', models.CharField(max_length=255, verbose_name='Nome Company')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('district', models.CharField(max_length=255, verbose_name='District')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name_company'],
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Phone')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Date Register')),
                ('last_login', models.DateField(auto_now_add=True, verbose_name='Last Access')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Admin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('about', models.TextField(blank=True)),
                ('education', models.CharField(blank=True, choices=[('Fundamental', 'Fundamental'), ('Médio', 'Medio'), ('Superior', 'Superior'), ('Pós Graduação', 'Pós Graduação'), ('Metrado', 'Metrado'), ('Doutorado', 'Doutorado')], max_length=50, verbose_name='Education')),
                ('level', models.CharField(blank=True, choices=[('Incompleto', 'Incompleto'), ('Completo', 'Completo'), ('Cursando', 'Cursando')], max_length=50, verbose_name='Level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curriculums',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_actual', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=255)),
                ('responsibilities', models.TextField()),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='core.curriculummodel')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['company'],
            },
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('id_job', models.CharField(default='', max_length=255, verbose_name='ID Job')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Urgent')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='Confidential')),
                ('is_pcd', models.BooleanField(default=False, verbose_name='Only PCD')),
                ('is_master_class', models.BooleanField(default=False, verbose_name='Master Class')),
                ('requirements', models.TextField(default='', verbose_name='Requirements')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Register Date')),
                ('end_registration_date', models.DateField(blank=True, null=True, verbose_name='End Registration Date')),
                ('benefits', models.TextField(default='', verbose_name='Benefits')),
                ('time_scale', models.CharField(default='', max_length=255, verbose_name='Time Scale')),
                ('remuneration', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remuneration')),
                ('count_applications', models.IntegerField(default=0, verbose_name='Applications Count')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='core.companymodel')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['title', '-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_date', models.DateField(auto_now_add=True, verbose_name='Application Date')),
                ('status', models.CharField(choices=[('Confirmada', 'Confirmada'), ('Selecionada', 'Selecionada'), ('Não Selecionada', 'Não Selecionada'), ('Finalizada', 'Finalizada')], max_length=30, verbose_name='Status')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_applications', to='core.curriculummodel')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='core.jobmodel')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['job', 'curriculum'],
            },
        ),
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='core.curriculummodel')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QualificationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='core.curriculummodel')),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
                'ordering': ['name'],
            },
        ),
    ]
